# Generated by Django 5.2.7 on 2025-10-31 14:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('swiyu', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Initiative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('closed', 'Closed'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_initiatives', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Initiative',
                'verbose_name_plural': 'Initiatives',
                'ordering': ['-created_at'],
                'permissions': [('can_create_initiative', 'Can create initiatives'), ('can_view_initiative_totals', 'Can view initiative signature totals')],
            },
        ),
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bfs_number', models.IntegerField(db_index=True, help_text='Official BFS number', unique=True)),
                ('name', models.CharField(help_text='Municipality name (Gemeindename)', max_length=255)),
                ('canton', models.CharField(help_text='Canton abbreviation (e.g., ZH, BE)', max_length=2)),
                ('postal_code', models.CharField(blank=True, help_text='Primary postal code', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Municipality',
                'verbose_name_plural': 'Municipalities',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['bfs_number'], name='core_munici_bfs_num_4747fb_idx'), models.Index(fields=['canton', 'name'], name='core_munici_canton_5b1e1c_idx')],
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('swiyu_profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='swiyu.swiyuuserprofile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='participant_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Participant',
                'verbose_name_plural': 'Participants',
            },
        ),
        migrations.CreateModel(
            name='Signature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('given_name', models.CharField(max_length=255)),
                ('family_name', models.CharField(max_length=255)),
                ('birth_date', models.DateField()),
                ('address', models.TextField()),
                ('id_number', models.CharField(help_text='National ID or similar', max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('signed_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('initiative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='core.initiative')),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='signatures', to='core.municipality')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='core.participant')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_signatures', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Signature',
                'verbose_name_plural': 'Signatures',
                'ordering': ['-signed_at'],
                'permissions': [('can_review_signatures', 'Can review signatures')],
                'indexes': [models.Index(fields=['initiative', 'status'], name='core_signat_initiat_5c71ce_idx'), models.Index(fields=['municipality', 'status'], name='core_signat_municip_f668fa_idx'), models.Index(fields=['participant', 'initiative'], name='core_signat_partici_1a677c_idx')],
                'unique_together': {('initiative', 'participant')},
            },
        ),
    ]
