# Generated by Django 5.2.7 on 2025-11-01 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='initiative',
            name='banner_image',
            field=models.ImageField(blank=True, help_text='Optional banner image', null=True, upload_to='initiative_banners/'),
        ),
        migrations.AddField(
            model_name='initiative',
            name='collection_end_date',
            field=models.DateTimeField(blank=True, help_text='When signature collection ends', null=True),
        ),
        migrations.AddField(
            model_name='initiative',
            name='collection_start_date',
            field=models.DateTimeField(blank=True, help_text='When signature collection starts', null=True),
        ),
        migrations.AddField(
            model_name='initiative',
            name='target_signatures',
            field=models.IntegerField(default=0, help_text='Number of signatures required'),
        ),
        migrations.AddField(
            model_name='initiative',
            name='url',
            field=models.URLField(blank=True, help_text='External URL with more information', max_length=500),
        ),
    ]
