# Generated by Django 5.2.7 on 2025-11-01 12:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initiative_banner_image_and_more'),
        ('swiyu', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='ahv_number',
            field=models.CharField(blank=True, db_index=True, help_text='Swiss AHV/AVS social security number', max_length=16, null=True),
        ),
        migrations.AddIndex(
            model_name='participant',
            index=models.Index(fields=['ahv_number'], name='core_partic_ahv_num_579ac2_idx'),
        ),
    ]
