# Generated by Django 5.2.7 on 2025-11-01 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_participant_ahv_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='signature',
            name='postal_code',
            field=models.CharField(blank=True, help_text='PLZ', max_length=10),
        ),
        migrations.AddField(
            model_name='signature',
            name='street_and_number',
            field=models.CharField(blank=True, help_text='Strasse und Hausnummer', max_length=255),
        ),
        migrations.AlterField(
            model_name='signature',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='signature',
            name='id_number',
            field=models.CharField(blank=True, help_text='National ID or similar', max_length=100),
        ),
    ]
