# Generated by Django 5.2.7 on 2025-11-01 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_signature_postal_code_signature_street_and_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='initiative',
            name='initiative_committee',
            field=models.TextField(blank=True, help_text='Initiative committee members and their right to withdraw'),
        ),
    ]
