# Generated by Django 5.2.7 on 2025-10-31 14:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SwiyuUserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('given_name', models.CharField(max_length=255)),
                ('family_name', models.CharField(max_length=255)),
                ('birth_date', models.DateField()),
                ('birth_place', models.CharField(max_length=255)),
                ('eid_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('verified_at', models.DateTimeField(auto_now_add=True)),
                ('last_verified', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='swiyu_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Swiyu User Profile',
                'verbose_name_plural': 'Swiyu User Profiles',
            },
        ),
        migrations.CreateModel(
            name='SwiyuVerification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('verification_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('verification_url', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('verified_claims', models.JSONField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['verification_id'], name='swiyu_swiyu_verific_3c1efe_idx'), models.Index(fields=['status', 'created_at'], name='swiyu_swiyu_status_f21a95_idx')],
            },
        ),
    ]
