# Generated by Django 5.2.7 on 2025-11-01 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swiyu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swiyuuserprofile',
            name='birth_place',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
